# Generated by Django 4.1 on 2022-08-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVTalfonso', '0002_alter_integrantes_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
