# Generated by Django 4.1 on 2022-08-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVTalfonso', '0003_alter_familia_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
